# Generated by Django 5.0.3 on 2024-04-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesreturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreturn',
            name='reason',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
